/*
 */

package antgame.gui;

/**
 *
 * @author jay-to-the-dee <jay-to-the-dee@users.noreply.github.com>
 */
public class GameStatsPanel extends javax.swing.JPanel
{

    /**
     * Creates new form GameStatsPanel
     */
    public GameStatsPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        blackLabel = new javax.swing.JLabel();
        redLabel = new javax.swing.JLabel();
        foodLabel = new javax.swing.JLabel();
        aliveAntsLabel = new javax.swing.JLabel();
        restingLabel = new javax.swing.JLabel();

        setName("Game Stats"); // NOI18N
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 7, 0, 7, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        blackLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        blackLabel.setText("Black");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(blackLabel, gridBagConstraints);

        redLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        redLabel.setForeground(new java.awt.Color(255, 0, 0));
        redLabel.setText("Red");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        add(redLabel, gridBagConstraints);

        foodLabel.setText("Food");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(foodLabel, gridBagConstraints);

        aliveAntsLabel.setText("Alive ants");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(aliveAntsLabel, gridBagConstraints);

        restingLabel.setText("Resting");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(restingLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aliveAntsLabel;
    private javax.swing.JLabel blackLabel;
    private javax.swing.JLabel foodLabel;
    private javax.swing.JLabel redLabel;
    private javax.swing.JLabel restingLabel;
    // End of variables declaration//GEN-END:variables
}
