package antgame.gui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import mainPackage.TournamentFile;

/**
 *
 * @author jay-to-the-dee <jay-to-the-dee@users.noreply.github.com>
 */
public class TournamentStatsFloat extends javax.swing.JPanel
{

    private ArrayList<TournamentFile> tournamentFiles;

    /**
     * Creates new form TournamentStatusFloat
     */
    public TournamentStatsFloat()
    {
        initComponents();
    }

    public void setTournamentFiles(ArrayList tournamentFiles)
    {
        this.tournamentFiles = tournamentFiles;
    }

    public void updateTable()
    {
        //Clear table
        DefaultTableModel model = (DefaultTableModel) statsTable.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--)
        {
            model.removeRow(i);
        }

        for (TournamentFile tournamentFile : tournamentFiles)
        {
            model.addRow(new Object[]
            {
                tournamentFile.toString(), tournamentFile.getWins(), tournamentFile.getDraws(), tournamentFile.getLoses()
            });
        }
    }


/**
 * This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        statsTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout(5, 5));

        statsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Brain", "W", "D", "L"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(statsTable);
        if (statsTable.getColumnModel().getColumnCount() > 0)
        {
            statsTable.getColumnModel().getColumn(0).setMinWidth(50);
            statsTable.getColumnModel().getColumn(0).setPreferredWidth(175);
            statsTable.getColumnModel().getColumn(1).setResizable(false);
            statsTable.getColumnModel().getColumn(1).setPreferredWidth(20);
            statsTable.getColumnModel().getColumn(2).setResizable(false);
            statsTable.getColumnModel().getColumn(2).setPreferredWidth(20);
            statsTable.getColumnModel().getColumn(3).setResizable(false);
            statsTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTextArea1.setColumns(15);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable statsTable;
    // End of variables declaration//GEN-END:variables
}
